First draft of NoSQL
Maxwell-Yang-2001/QuickBite pull request #1
Opened 2023-05-21 05:01 UTC by ThomasSong99

2023-05-21 05:08 UTC, Maxwell-Yang-2001 commented on designs/NoSQL_note.md
> + - id: `string`
Do we also want to consider names? That might be different from the id, which can be just alphanumerical gibberish.

2023-05-21 05:09 UTC, Maxwell-Yang-2001 commented on designs/NoSQL_note.md
> + - address: Unit 123 23th street, Vancouver,BC
```suggestion
 - address: Unit 123 23th street, Vancouver, BC
```

2023-05-21 05:09 UTC, Maxwell-Yang-2001 commented on designs/NoSQL_note.md
> + - restaurant_id: `string`
Same comment regarding name as above.

2023-05-21 05:10 UTC, Maxwell-Yang-2001 commented on designs/NoSQL_note.md
> + - content : `list[string]`
```suggestion
 - content: `List[string]`
```

2023-05-21 05:11 UTC, Maxwell-Yang-2001 commented on designs/NoSQL_note.md
> + - extra_charge: `string`
This can be a number as it is just a numerical value. Then maybe the currency can be separated out as a different field.

2023-05-21 05:12 UTC, Maxwell-Yang-2001 commented on designs/NoSQL_note.md
> + ####Example:
```suggestion
 #### Example:
```

2023-05-21 05:13 UTC, Maxwell-Yang-2001 commented on designs/NoSQL_note.md
> + - content: [dish_name: fry_chicken, unit price: $5, amount: 3]
```suggestion
 - content: [{dish_name: fry_chicken, unit_price: $5, amount: 3}]
```

2023-05-21 05:14 UTC, Maxwell-Yang-2001 commented on designs/NoSQL_note.md
> + - restaurant_id: `string`
We can remove a lot of the `restaurant_` prefixes here.

2023-05-21 05:14 UTC, Maxwell-Yang-2001 commented on designs/NoSQL_note.md
> + - Menu: `list[string] & picture`
```suggestion
 - Menu: `List[object]`
```

2023-05-21 05:15 UTC, Maxwell-Yang-2001 commented on designs/NoSQL_note.md
> + - schedule: 11:00am - 8pm
```suggestion
 - schedule: 11:00am - 8:00pm
```

2023-05-21 05:15 UTC, Maxwell-Yang-2001 commented on designs/NoSQL_note.md
> + - restaurant_address: 1234 West 21th street,
```suggestion
 - restaurant_address: 1234 West 21th street
```

2023-05-21 05:15 UTC, Maxwell-Yang-2001 commented on designs/NoSQL_note.md
> + - Menu: [ dish_name:Fried rice, unite_price: $10, dish_description: ingredients, dish_picture: xxx.png]
```suggestion
 - Menu: [{dish_name: Fried rice, unite_price: $10, dish_description: ingredients, dish_picture: xxx.png}]
```

2023-05-21 05:18 UTC, Maxwell-Yang-2001 commented on designs/NoSQL_note.md
> + - schedule: `time`
Just leave as a TODO for now: time means a timestamp only. The actual schedule can be relatively complex.
```suggestion
 - schedule: `TODO`
```

2023-05-21 05:18 UTC, Maxwell-Yang-2001 commented on designs/NoSQL_note.md
> + - driver_id: `string`
same comment as removing the prefixes as above.

2023-05-21 05:19 UTC, Maxwell-Yang-2001 commented on designs/NoSQL_note.md
> + - driver_image: `picture`
Missing order_ids.

2023-05-21 05:19 UTC, Maxwell-Yang-2001 commented on designs/description.md
> +![ERD](sql_early_design2.png)
Now that this NOSQL_note is added, we should also mention it in this doc.

2023-05-21 05:20 UTC, Maxwell-Yang-2001 requested changes
Some required changes noted in the comments.

2023-05-22 02:03 UTC, ThomasSong99 commented
Hi, I have addressed your comments and also refined some of the examples to use JSON format for better readability.Please take a look.

2023-05-22 02:04 UTC, Maxwell-Yang-2001 approved these changes
LGTM! Please merge.

2023-05-22 02:04 UTC, merged